Add new events that allow for better API usage
Oxywire/OxyTowns pull request #3
Opened 2024-04-19 20:10 UTC by Golfing7

Adds some new events and improves the event API

2024-04-20 22:04 UTC, SirSalad requested changes

2024-04-20 22:04 UTC, SirSalad commented on src/main/java/com/oxywire/oxytowns/events/TownDisbandEvent.java
> +public class TownDisbandEvent extends TownPlayerEvent implements Cancellable {
This should also be fired on `com.oxywire.oxytowns.command.commands.admin.town.TownDisbandCommand`

2024-04-20 22:04 UTC, SirSalad commented on src/main/java/com/oxywire/oxytowns/events/TownDisbandEvent.java
> +    /** The player disbanding the town */
Do we need this context? Towns will only ever be naturally disbanded by the mayor or a server admin

2024-05-17 21:00 UTC, Golfing7 commented
Made the adjustments. Thanks for the feedback. I apologize for the long wait.

2025-03-04 20:17 UTC, closed without merging